Models/ViewModels/LineTracking/BackEnd_StatusViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IRS.Models.ViewModels.LineTracking
{
    public class BackEnd_StatusViewModel
    {
        public string Linea_Assy { get; set; }
        public DateTime Assy_F { get; set; }
        public string StatusAssy1 { get; set; }
    }
}

Models/ViewModels/LineTracking/FileScannerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IRS.Models.ViewModels.LineTracking
{
    public class FileScannerViewModel
    {

        public string LineID { get; set; }
        public DateTime Marker { get; set; }
        public DateTime SPI {  get; set; }  
        public DateTime AOI { get; set; }
        public DateTime AssyFiles {  get; set; }    
        public string Area { get; set; }
        public short Active { get; set; }     
        public string IDSPI { get; set; }
        public string LineType { get; set; }

    }
}

Models/ViewModels/LineTracking/Smt_StatusViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using IRS.Models;

namespace IRS.Models.ViewModels.LineTracking
{
    public class Smt_StatusViewModel
    {
        public string Linea { get; set; }
        public string WO { get; set; }
        public DateTime Marcadora_f   { get; set; }

        public DateTime SPI_f { get; set; }
        public DateTime AOI_f { get; set; }

        public int Marcadora { get; set; }

        public int SPI { get; set; }
        public int AOI { get; set; }

        public string Pick_place { get; set; }

        public string Oee_detail {  get; set; }

        public int Top {  get; set; }
        public int Bot { get; set; }



    }
   
}

Controllers/LineTrackingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IRS.Models;
using IRS.Models.ViewModels.LineTracking;
using IRS.Services.LineTracking;

namespace IRS.Controllers
{
    public class LineTrackingController : Controller
    {
        // GET: LineTracking
        public ActionResult Index()
        {
            GetinfoService getinfo = new GetinfoService();
            ViewBag.Lista = getinfo.Get_Status();
            var Lista= getinfo.Get_Status();

            ViewBag.Lista_BackEnd = getinfo.Get_StatusAssy();
            var Lista_BackEnd = getinfo.Get_StatusAssy();

            ViewBag.Lista_Servicios=getinfo.Get_Services_Status();
            
            return View(Lista);
        }

        public ActionResult OeeSMT(int? mcid/*, DateTime date*/)
        {
            /* CBSEntities db = new CBSEntities();
             var turno=db.Database.SqlQuery<int>("exec TurnoA").FirstOrDefault();
             ViewBag.turno = turno;*/

            vManageEntities db2 = new vManageEntities();
            var day = DateTime.Now;
            var dia = day.ToString("yyyy-MM-dd");
            var dia3 = day.AddDays(-1).ToString("yyyy-MM-dd");
            ViewBag.turno1 = db2.XOEE_Details_Per_Hour.Where(x => x.McID == mcid && x.TurnoID==1 && x.TimeDate.ToString()==dia ).ToList();
            ViewBag.turno2 = db2.XOEE_Details_Per_Hour.Where(x => x.McID == mcid && x.TurnoID == 2 && x.TimeDate.ToString() == dia).ToList();
            ViewBag.turno3 = db2.XOEE_Details_Per_Hour.Where(x => x.McID == mcid && x.TurnoID == 3 && x.TimeDate.ToString() == dia3).ToList();


            return View();
        }
    }
}

Views/LineTracking/Index.cshtml
@model List<IRS.Models.ViewModels.LineTracking.Smt_StatusViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutClean.cshtml";

}

<link rel="stylesheet" href="~/Content/Tema.css" />
 <style>
     .general{
         padding-top:1rem;
     }
     .banners{
         width:3rem;
         text-align:center;
        float:right;
     }
     .fondo-tabla{
         background-color:#0066a1  !important;
         
     }

 </style>
<div class="container-fluid general">
    <div><h1 class="text-center">Resumen de Produccion</h1></div>
    <div class="row">
        <div class="col-12">
            <table class="table table-responsive border border-2">
                <thead class="border">
                    <tr>
                        <th class="fondo-tabla text-white">Línea</th>
                        <th class="fondo-tabla text-white">Orden de trabajo</th>
                        <th class="fondo-tabla text-white">Marcadora</th>
                        <th class="fondo-tabla text-white">SPI</th>
                        <th class="fondo-tabla text-white">Pick & PLace</th>
                        <th class="fondo-tabla text-white">AOI</th>
                        <th class="fondo-tabla text-white">OEE</th>
                        <th class="fondo-tabla text-white">Tiempo muerto</th>
                        <th class="fondo-tabla text-white">Piezas OK </th>
                        <th class="fondo-tabla text-white">Piezas en búfer</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var x in Model)
                    {
                        var mcid = x.Linea.Contains("(") ?
                            x.Linea.Substring(x.Linea.IndexOf("(") + 1 ):
                            x.Linea;
                        mcid = mcid.Replace(")", string.Empty);
                        <tr>

                            <td>@Html.ActionLink("" + x.Linea, "OeeSMT", "LineTracking", new { mcid = mcid }, null)</td>
                            <td>@x.WO</td>
                            @if (x.Marcadora >= 3)
                            {
                                <td>@x.Marcadora_f <label class="bg-danger rounded-3 banners text-white"> NOK</label></td>
                            }
                            else
                            {
                                <td>@x.Marcadora_f <label class="bg-success rounded-3 banners text-white"> OK</label></td>
                            }

                            @if (x.SPI >= 3)
                            {
                                <td>@x.SPI_f <label class="bg-danger rounded-3 banners text-white"> NOK</label></td>
                            }
                            else
                            {
                                <td>@x.SPI_f <label class="bg-success rounded-3 banners text-white"> OK</label></td>
                            }
                            <td>@x.Pick_place</td>
                            @if (x.AOI >= 3)
                            {
                                <td>@x.AOI_f <label class="bg-danger rounded-3 banners text-white"> NOK</label></td>
                            }
                            else
                            {
                                <td>@x.AOI_f <label class="bg-danger rounded-3 banners text-white"> OK</label></td>
                            }
                            <td>70%</td>
                            <td>40 min</td>
                            <td>150</td>
                            <td>T @x.Top B @x.Bot </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
       
    </div>
 
    
    <br />

   

        <div class="row">
           
            <div class="col-5">
                <table class="table">
                    <thead class="table-dark">
                        <tr>
                            <th>Servicio</th>
                            <th>Estatus</th>
                        </tr>
                        </thead>
                    <tbody>
                        @foreach(var y in ViewBag.Lista_Servicios)
                        {
                           <tr>
                               <td>@y.Alias </td>
                               @if (y.Estatus.ToLower() == "running")
                               {

                                   <td> <label class="bg-success rounded-3 banners text-white"> OK</label></td>
                               }
                               else
                               {
                                   <td> <label class="bg-danger rounded-3 banners text-white"> NOK</label></td>
                               }
                           </tr>
                         }
                        


                    </tbody>

                </table>
            </div>
        </div>
       

</div>

Views/LineTracking/OeeSMT.cshtml
@{
    ViewBag.Title = "OeeSMT";
    Layout = "~/Views/Shared/_LayoutClean.cshtml";
}
<link rel="stylesheet" href="~/Content/Tema.css" />
<style>
    .general {
        padding-top: 1rem;
    }

    .banners {
        width: 3rem;
        text-align: center;
        float: right;
    }

    .fondo-tabla {
        background-color: #0066a1 !important;
    }
</style>
<div class="container-fluid">
    <h1 class="text-center">Detalles de Produccion</h1>
</div>

<br />

<div class="container-fluid general">
    <h1 class="text-center">Espacio para Filtrar linea y fechas @ViewBag.turno</h1>
    <div class="row">
       
        <div class="row">
            <div class="col-4">
                <table class="table table-responsive border border-2">
                    <thead class="table-dark">
                        PRIMER TURNO
                        <tr>
                            <th class="fondo-tabla text-white">Hora</th>
                            <th class="fondo-tabla text-white">Objetivo</th>
                            <th class="fondo-tabla text-white">Actual</th>
                            <th class="fondo-tabla text-white">Tiempo Muerto</th>
                            <th class="fondo-tabla text-white">OEE</th>
                            <th class="fondo-tabla text-white">Programa</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var a in ViewBag.turno1)
                         {
                            <tr>
                                <td>@a.Hora</td>
                                <td>@a.TPz</td>
                                @if (a.PzOk >= a.TPz)
                                {
                                    <td><label class="bg-success rounded-3 banners text-white">@a.PzOk </label></td>
                                }
                                else
                                {
                                    <td><label class="bg-danger rounded-3 banners text-white">@a.PzOk </label></td>
                                }

                                @if (a.DownTime <= 20)
                                {
                                    <td><label class="bg-success rounded-3 banners text-white">@a.DownTime</label></td>
                                }
                                else
                                {
                                    <td><label class="bg-danger rounded-3 banners text-white">@a.DownTime</label></td>
                                }

                                @if (a.OEE >= 80)
                                {
                                    <td><label class="bg-success rounded-3 banners text-white">@a.OEE</label></td>
                                }
                                else
                                {
                                    <td><label class="bg-danger rounded-3 banners text-white"> @a.OEE</label></td>
                                }


                              <td>@a.Programa</td>
                            </tr>
                         }

                    </tbody>
                </table>
            </div>
            <div class="col-4">
                <table class="table table-responsive border border-2">
                    <thead class="table-dark">
                        SEGUNDO TURNO
                        <tr>
                            <th class="fondo-tabla text-white">Hora</th>
                            <th class="fondo-tabla text-white">Objetivo</th>
                            <th class="fondo-tabla text-white">Actual</th>
                            <th class="fondo-tabla text-white">Tiempo Muerto</th>
                            <th class="fondo-tabla text-white">OEE</th>
                            <th class="fondo-tabla text-white">Programa</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var a in ViewBag.turno2)
                        {
                            <tr>
                                <td>@a.Hora</td>
                                <td>@a.TPz</td>
                                @if (a.PzOk >= a.TPz)
                                {
                                    <td><label class="bg-success rounded-3 banners text-white">@a.PzOk </label></td>
                                }
                                else
                                {
                                    <td><label class="bg-danger rounded-3 banners text-white">@a.PzOk </label></td>
                                }

                                @if (a.DownTime <= 20)
                                {
                                    <td><label class="bg-success rounded-3 banners text-white">@a.DownTime</label></td>
                                }
                                else
                                {
                                    <td><label class="bg-danger rounded-3 banners text-white">@a.DownTime</label></td>
                                }

                                @if (a.OEE >= 80)
                                {
                                    <td><label class="bg-success rounded-3 banners text-white">@a.OEE</label></td>
                                }
                                else
                                {
                                    <td><label class="bg-danger rounded-3 banners text-white"> @a.OEE</label></td>
                                }


                                <td>@a.Programa</td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
            <div class="col-4">
                <table class="table table-responsive border border-2">
                    <thead class="table-dark">
                        TERCER TURNO
                        <tr>
                            <th class="fondo-tabla text-white">Hora</th>
                            <th class="fondo-tabla text-white">Objetivo</th>
                            <th class="fondo-tabla text-white">Actual</th>
                            <th class="fondo-tabla text-white">Tiempo Muerto</th>
                            <th class="fondo-tabla text-white">OEE</th>
                            <th class="fondo-tabla text-white">Programa</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var a in ViewBag.turno3)
                        {
                            <tr>
                                <td>@a.Hora</td>
                                <td>@a.TPz</td>
                                @if (a.PzOk >= a.TPz)
                                {
                                    <td><label class="bg-success rounded-3 banners text-white">@a.PzOk </label></td>
                                }
                                else
                                {
                                    <td><label class="bg-danger rounded-3 banners text-white">@a.PzOk </label></td>
                                }

                                @if (a.DownTime <= 20)
                                {
                                    <td><label class="bg-success rounded-3 banners text-white">@a.DownTime</label></td>
                                }
                                else
                                {
                                    <td><label class="bg-danger rounded-3 banners text-white">@a.DownTime</label></td>
                                }

                                @if (a.OEE >= 80)
                                {
                                    <td><label class="bg-success rounded-3 banners text-white">@a.OEE</label></td>
                                }
                                else
                                {
                                    <td><label class="bg-danger rounded-3 banners text-white"> @a.OEE</label></td>
                                }


                                <td>@a.Programa</td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>