Controllers/ProcessController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Web;
using System.Web.Mvc;
using IRS.Models;
using IRS.Models.ViewModels;
using IRS.Services;
using Microsoft.Ajax.Utilities;

/// <summary>
/// M Olvera and J Montoya are in charge
/// </summary>
namespace IRS.Controllers
{
    public class ProcessController : Controller
    {
        readonly ValorServices oService = new ValorServices();
        readonly public vManageEntities db_vmanage = new vManageEntities();

        //¡¡¡¡ Controllers para Vistas de PROCESS
        public ActionResult Equipment_Repair() { return View(); }
        public ActionResult Kamishibai_Board() { return View(); }
        public ActionResult Audit_Controls () { return View(); }
        public ActionResult Valor_Apps() { return View(); }

        //¡¡¡¡ Controllers para Vistas de PROCESS para sub operaciones de VALOR_APPS
        public ActionResult Declaration_Errors() 
        {
            //var model = oService.Declaration_Errors();
            return View(); 
        }
        public ActionResult DowntimeEntry() { return View(); }
        public ActionResult Kiosk_Configuration() { return View(); }
        public ActionResult Error_Codes() { return View(); }
        public ActionResult PLC_Activation() { return View(); }
        public ActionResult OEE_Reporting() { return View(); }
        public ActionResult System_Erros() { return View(); }
        public ActionResult Trace_Errors() 
        {
            var model = oService.LogErrores();
            return View(model); 
        }
        public ActionResult History_Check(string serie="1") 
        {
            string query;
            if (serie == "1" || serie =="")
            {
                query = "SELECT A.SerialNumber, Convert(int,A.Sequence) as Sequence , A.TimeDone, A.Message, A.LineID, A.StationID, B.PN FROM (SELECT top (1000)ID,SerialNumber,Message, LineID, StationID, Sequence, TimeDone, Result, AliasSerialNumber FROM dbo.XHistoryCheck WHERE (SerialNumber<>'') ORDER BY TimeDone DESC) AS A INNER JOIN dbo.XCuadranteDisplay2 AS B ON A.SerialNumber = B.SN_PCB_Main ORDER BY TimeDone DESC";
            }
            else
            {

                query = "SELECT A.SerialNumber, Convert(int,A.Sequence) as Sequence , A.TimeDone, A.Message, A.LineID, A.StationID, B.PN FROM (SELECT top (1000)ID,SerialNumber,Message, LineID, StationID, Sequence, TimeDone, Result, AliasSerialNumber FROM dbo.XHistoryCheck WHERE (SerialNumber='" + serie+"') ORDER BY TimeDone DESC) AS A INNER JOIN dbo.XCuadranteDisplay2 AS B ON A.SerialNumber = B.SN_PCB_Main";
            }

            var result= db_vmanage.Database.SqlQuery<XHistoryCheck>(query).ToList();

            return View(result); 
        }

        public ActionResult ComponentTrace(string busqueda="1")
        {
            string query;
            if (busqueda == "1")
            {
                //Tabla que muestra los prmieros 200 registros de la tabla CompList sin filtro
                query = "SELECT TOP (200) [CompID],[FeederID],[CompName],[OpenTimeStamp],[NumDryLeft],[McID],[Station],[Slot],[SubSlot],[Used],[Errors],[Amount],[Status],[LastSeenOnMachine] FROM [vManage].[dbo].[CompList] ORDER BY DryTimeStamp DESC";
            }
            else
            {
                //Tabla que muestra los registros filtrados por CompID
                query = "SELECT [CompID],[FeederID],[CompName],[OpenTimeStamp],[NumDryLeft],[McID],[Station],[Slot],[SubSlot],[Used],[Errors],[Amount],[Status],[LastSeenOnMachine] FROM [vManage].[dbo].[CompList] WHERE (CompID='" + busqueda + "' or CompName='" + busqueda +"' or FeederID='" + busqueda +"') ORDER BY DryTimeStamp DESC";
            }
            var result = db_vmanage.Database.SqlQuery<ListaComponentes>(query).ToList();
            return View(result);

        }
        public ActionResult History_Check_Selectivos(string serie = "1")
        {
            string query;
            if (serie == "1")
            {
                query = "SELECT A.SerialNumber, Convert(int,A.Sequence) as Sequence , A.TimeDone, A.Message, A.LineID, A.StationID FROM (SELECT top (50)ID,SerialNumber,Message, LineID, StationID, Sequence, TimeDone, Result, AliasSerialNumber FROM dbo.XHistoryCheck WHERE (SerialNumber<>'' AND (StationID='XRAY' OR StationID='ROUTER' OR StationID='OBP')) ORDER BY TimeDone DESC) AS A  ORDER BY TimeDone DESC";
            }
            else
            {

                query = "SELECT A.SerialNumber, Convert(int,A.Sequence) as Sequence , A.TimeDone, A.Message, A.LineID, A.StationID FROM (SELECT top (100)ID,SerialNumber,Message, LineID, StationID, Sequence, TimeDone, Result, AliasSerialNumber FROM dbo.XHistoryCheck WHERE (SerialNumber='" + serie + "' AND (StationID='XRAY' OR StationID='ROUTER' OR StationID='OBP')) ORDER BY TimeDone DESC) AS A";
            }

            var result = db_vmanage.Database.SqlQuery<XHistoryCheck>(query).ToList();

            return View(result);
        }

        public ActionResult Trace_Desactivation() { return View(); }
        public ActionResult Valor_Declaration() { return View(); }

        public ActionResult ComponentAndPCB(string busqueda = "1")
        {
            string query;
            if (busqueda == "1")
            {
                //Tabla que muestra los prmieros 200 registros de la tabla DeviceTrace sin filtro
                query = "SELECT TOP (200) [DeviceID],[McID],[Station],[Slot],[SubSlot],[CompID],[BlockNo],[CompType],[InsertDate] FROM [vManage].[dbo].[DeviceTrace] ORDER BY InsertDate DESC";
            }
            else
            {
                //Tabla que muestra los registros filtrados por CompID
                query = "SELECT [DeviceID],[McID],[Station],[Slot],[SubSlot],[CompID],[BlockNo],[CompType],[InsertDate] FROM [vManage].[dbo].[DeviceTrace] WHERE (CompID='" + busqueda + "' or McID='" + busqueda + "') ORDER BY InsertDate DESC";
            }
            var result = db_vmanage.Database.SqlQuery<ListaComponentesPCB>(query).ToList();
            return View (result);
        }

        //¡¡¡¡ Action and View Result para Formulario de Declaration Program > CRUD
        public ViewResult Declaration_Programs() 
        {
            //Tabla que muestra todos los registros de la tabla <XDeclarationProgram>
            var query = oService.xDeclaration_Programs();
           
            return View(query); 
        }
        public ViewResult Declaration_Program_formulario()
        {
            ViewBag.McID = db_vmanage.XDeclarationProgram.DistinctBy(a=>a.McID).Select(a=>a.McID).ToList();
           // ViewBag.Lineas = db_vmanage.XDeclarationProgram.DistinctBy(b => b.Line).Select(b => b.Line).ToList();
            ViewBag.Assy_Line=db_vmanage.XDeclarationProgram.DistinctBy(c => c.Assy_Line).Where(C=>C.Assy_Line!=null).Select(c => c.Assy_Line).ToList();
            ViewBag.Linea = db_vmanage.X_McID_Relationship.ToList();
            //Formulario para un nuevo registro
            return View();
        }
        public ActionResult Declation_Program_Insertar(XDeclarationProgram model)
        {
            var mcid = int.Parse((db_vmanage.X_McID_Relationship.Where(c => c.SMT == model.Line).Select(c=>c.McID).FirstOrDefault()));
            model.McID = mcid;
            //Action Result para insertar en la tabla <XDeclarationProgram> el nuevo registro
            oService.Insertar(model);
            return RedirectToAction("Declaration_Programs");
        }
        public ActionResult Declation_Program_Editar_formulario(long dato)
        {
            ViewBag.Linea = db_vmanage.X_McID_Relationship.ToList();
            ViewBag.Assy_Line = db_vmanage.XDeclarationProgram.DistinctBy(c => c.Assy_Line).Where(C => C.Assy_Line != null).Select(c => c.Assy_Line).ToList();
            //Buscando, seleccionando y enviando el RecordID a MOSTRAR en la vista Declation_Program_Editar_formulario          
            var model = oService.Editar(dato);
            return View(model);
        }
        public ActionResult Declation_Program_Editar(XDeclarationProgram model)
        {
            ViewBag.Assy_Line = db_vmanage.XDeclarationProgram.DistinctBy(c => c.Assy_Line).Where(C => C.Assy_Line != null).Select(c => c.Assy_Line).ToList();
            var mcid = int.Parse((db_vmanage.X_McID_Relationship.Where(c => c.SMT == model.Line).Select(c => c.McID).FirstOrDefault()));
            model.McID = mcid;
            oService.Editar_Form(model);
            return RedirectToAction("Declaration_Programs");
        }
        public ActionResult Declation_Program_Eliminar(long dato)
        {
            //Action Result para eliminar en la tabla <XDeclarationProgram> el registro
            oService.Eliminar(dato);
            return RedirectToAction("Declaration_Programs");
        }
    }
}

Views/Process/Audit_Controls.cshtml
@{
    ViewBag.Title = "Audit_Controls";
}

<h2>Audit_Controls</h2>

Views/Process/ComponentAndPCB.cshtml
@{
    ViewBag.Title = "ComponentAndPCB";
}

<h1 class="text-primary fw-bold">Registro de Componentes por PCB</h1>
<hr />

<form action="ComponentAndPCB" method="post">
    <input type="text" name="busqueda" value="" />
    <input type="submit" value="Buscar">
    <label class="shadow fw-bold"> *Puede buscar por: ID de rollo de material </label>
</form>
<br />
<table class="table table-striped table-bordered" id="tabla_desplegada">
    <thead>
        <tr class="table-primary">
            <th scope="col">ID Componente</th>
            <th scope="col">McID</th>
            <th scope="col">Estacion</th>
            <th scope="col">Ranura</th>
            <th scope="col">SubRanura</th>
            <th scope="col">Numero de serie de PCB</th>
            <th scope="col">Bloque dentro del panel</th>
            <th scope="col">Tipo de Componente</th>
            <th scope="col">Fecha de insercion</th>           
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.CompID</td>
                <td>@x.McID</td>
                <td>@x.Station</td>
                <td>@x.Slot</td>
                <td>@x.SubSlot</td>
                <td>@x.DeviceID</td>
                <td>@x.BlockNo</td>
                <td>@x.CompType</td>
                <td>@x.InsertDate</td>                
            </tr>
        }
    </tbody>
    <tr class="noSearch hide fw-bold">
        <td colspan="11"></td>
    </tr>
</table>
<script src="~/Scripts/Buscar.js"></script>

Views/Process/ComponentTrace.cshtml
@{
    ViewBag.Title = "ComponentTrace";
}

<h1 class="text-primary fw-bold">Registro de Componentes</h1>
<hr />

    <form action="ComponentTrace" method="post">
        <input type="text" name="busqueda" value="" />
        <input type="submit" value="Buscar">
        <label class="shadow fw-bold"> *Puede buscar por:   ID de Componente,       FeederID o  Nombre del componente</label>
    </form>
    <br />
    <table class="table table-striped table-bordered" id="tabla_desplegada">
        <thead>
            <tr class="table-primary">
                <th scope="col">ComponenteID</th>
                <th scope="col">FeederID</th>
                <th scope="col">Nombre de Componente</th>
                <th scope="col">Marca de tiempo abierto</th>
                <th scope="col">Horneados restantes</th>
                <th scope="col">Estacion McID</th>
                <th scope="col">Estacion</th>
                <th scope="col">Ranura</th>
                <th scope="col">SubRanura</th>
                <th scope="col">Veces usado</th>
                <th scope="col">Errores</th>
                <th scope="col">Cantidad</th>
                <th scope="col">Status</th>
                <th scope="col">Ultima estacion que lo registro</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var x in Model)
            {
                <tr>
                    <td>@x.CompID</td>
                    <td>@x.FeederID</td>
                    <td>@x.CompName</td>
                    <td>@x.OpenTimeStamp</td>
                    <td>@x.NumDryLeft</td>
                    <td>@x.McID</td>
                    <td>@x.Station</td>
                    <td>@x.Slot</td>
                    <td>@x.SubSlot</td>
                    <td>@x.Used</td>
                    <td>@x.Errors</td>
                    <td>@x.Amount</td>
                    <td>@x.Status</td>
                    <td>@x.LastSeenOnMachine</td>
                </tr>
            }
        </tbody>
        <tr class="noSearch hide fw-bold">
            <td colspan="11"></td>
        </tr>
    </table>
<script src="~/Scripts/Buscar.js"></script>

Views/Process/Declaration_Program_formulario.cshtml
@{
    ViewBag.Title = "Declaration_Program_formulario";
}

<h2>Registro de Programas de Produccion</h2>
<hr />
<form class="g-3 gx-5 gy-5" method="post" action="~/Process/Declation_Program_Insertar">
    <div class="container-fluid">
        <div class="row">

            <input type="hidden" name="mcid" value="1" />


            <!--SELECCION DE LINEA TOMANDO 5 COLUMNAS col-5 -->
            <div class="col-md-3">
                <label class="fs-4 fw-bold" for="Line">Linea de SMT:</label>
                <select class="form-control form-select" name="Line" required>
                    <option value="" disabled selected>Seleccione...</option>
                    @foreach (var l in ViewBag.Linea)
                    {
                        <option value="@l.SMT">@l.SMT </option>
                    }
                    <!--<option disabled selected>Seleccione....</option>-->
                </select>
            </div>
            <div class="col-md-5">
                <label class="fs-4 fw-bold" for="Program">Nombre del Programa:</label>
                <input type="text" class="form-control" name="Program" placeholder="Ejemplo >> 179_AB_C1_BOT" required/>
            </div>
            <div class="col-md-4">
                <label class="fs-4 fw-bold" for="Noblock"># de PCB dentro del Panel:</label>
                <input type="text" class="form-control" name="Noblock" placeholder="#piezas + 1" required />
            </div>

        </div>
        <br />
        <div class="row">

            <div class="col-md-3">
                <label class="fs-4 fw-bold" for="NIP">Codigo NIP:</label>
                <input type="text" class="form-control" name="NIP" required/>
            </div>
            <div class="col-md-5">
                <label class="fs-4 fw-bold" for="Suffix">Sufijo del Programa (Top/Botton):</label>
                <select class="form-control form-select" name="Suffix" required>
                    <option value="" disabled selected>Seleccione....</option>
                    <option>_T</option>
                    <option>_B</option>
                </select>
            </div>
            <div class="col-md-4">
                <label class="fs-4 fw-bold" for="PartNumber">Numero de Parte:</label>
                <input type="text" class="form-control" name="PartNumber" required />
            </div>

        </div>
        <br />

        <div class="row">


            <div class="col-md-3">
                <label class="fs-4 fw-bold" for="Assy_Line">Linea de Ensamble:</label>
                <select class="form-control form-select" name="Assy_Line" >
                    <option value="" disabled selected>Seleccione....</option>
                    @foreach (var a in ViewBag.Assy_Line)
                    {
                        <option class="order-first" value="@a">@a  </option>
                    }
                </select>
            </div>
            <div class="col-md-5">
                <label class="fs-4 fw-bold" for="CycleTime">Tiempo Ciclo (minutos):</label>
                <input type="text" class="form-control" name="CycleTime" placeholder="Ejemplo >> 0.251" />
            </div>
            <div class="col-md-4">
                <label class="fs-4 fw-bold" for="PzsHr">Piezas X Hora:</label>
                <input type="text" class="form-control" name="PzsHr" />
            </div>
        </div>
        <br />
        <div class="row">


            <div class="col-md-3">
              
                
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-2 ">
                <input type="submit" value="Crear" class="btn btn-success fs-4" name="name" />
             
            </div>
            <div class="col-2 ">
             
                <input type="reset" value="Resetear" class="btn btn-dark fs-4" name="name" />
            </div>  
        </div>
    </div>
</form>

Views/Process/Declaration_Programs.cshtml
@{
    ViewBag.Title = "Declaration_Programs";
}
<div class="container-fluid">
    <h1 class="text-primary fw-bold">Programas de Producción</h1>
    <hr />
  
        
            <div class="row">
                <div class="col-4">
                    <a href=@Url.Action("Declaration_Program_formulario" , "Process") class="btn btn-success fs-5">Nuevo programa</a>
                </div>
            </div>
            <div class="row">

            </div>
        
   
    <br />


    <div class="table-primary">
        <div class="row">
            <div class="col-4">
                <input id="searchTerm" onkeyup="doSearch()" type="text" class="form-control" placeholder="Escriba algo para filtrar" />
            </div>
           
        </div>
    </div>
    <br />
    <table class="table table-striped table-bordered" id="tabla_desplegada">
        <thead>
            <tr class="table-primary">
                <th scope="col">RecordID</th>
                <th scope="col">ID SMT</th>
                <th scope="col">Programa</th>
                <th scope="col">PCBs Panel</th>
                <th scope="col">NIP Code</th>
                <th scope="col">Suffix</th>
                <th scope="col">Num. de Parte</th>
                <th scope="col">SMT</th>
                <th scope="col">Linea Ensamble</th>
                <th scope="col">Tiempo Ciclo</th>
                <th scope="col">PzsHr</th>
                <th scope="col">Operaciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var x in Model)
            {
                <tr>
                    <td>@x.RecordID</td>
                    <td>@x.McID</td>
                    <td>@x.Program</td>
                    <td>@x.Noblock</td>
                    <td>@x.NIP</td>
                    <td>@x.Suffix</td>
                    <td>@x.PartNumber</td>
                    <td>@x.Line</td>
                    <td>@x.Assy_Line</td>
                    <td>@x.CycleTime</td>
                    <td>@x.PzsHr</td>
                    <td>
                        @Html.ActionLink("Editar ", "Declation_Program_Editar_formulario", "Process", new { dato = x.RecordID }, null)
                        @Html.ActionLink(" | Eliminar", "Declation_Program_Eliminar", "Process", new { dato = x.RecordID }, null)
                    </td>
                </tr>
            }
        </tbody>
        <tr class="noSearch hide fw-bold">
            <td colspan="11"></td>
        </tr>
    </table>
</div>
<script src="~/Scripts/Buscar.js"></script>

Views/Process/Downtime_Entry.cshtml
@{
    aViewBag.Title = "Downtime_Entry";
}
<h1>DownTime Entry</h1>
<hr />
<br />
<br />
<form class="row g-3 gx-5 gy-5">
    <!--SELECCION DE LINEA TOMANDO 5 COLUMNAS col-5 -->
    <div class="col-md-6">
        <label class="fs-3 fw-bold" for="Linea">Seleccione Linea:</label>
        <select class="form-control form-select" id="Linea">
            <option>Seleccione....</option>
            <option>SMT1</option>
            <option>SMT2</option>
            <option>SMT3</option>
            <option>SMT4</option>
            <option>SMT5</option>
            <option>SMT6</option>
            <option>SMT7</option>
            <option>SMT8</option>
            <option>MCA CLUSTER</option>
            <option>MCA DISPLAY</option>
        </select>
    </div>

    <div class="col-md-6">
        <label class="fs-3 fw-bold" for="Evento">Seleccione un Evento:</label>
        <select class="form-control form-select" id="Evento">
            <option>Seleccione....</option>
            <option>Evento 1 TBD</option>
            <option>Evento 2 TBD</option>
            <option>Evento 3 TBD</option>
            <option>Evento 4 TBD</option>
            <option>Evento 5 TBD</option>
        </select>
    </div>

    <div class="col-md-6">
        <label class="fs-3 fw-bold" for="Causa">Seleccione una Causa:</label>
        <select class="form-control form-select" id="Causa">
            <option>Seleccione....</option>
            <option>Causa 1</option>
            <option>Causa 2</option>
            <option>Causa 3</option>
            <option>Causa 4</option>
        </select>
    </div>

    <div class="col-md-6">
        <label class="fs-3 fw-bold" for="Maquina">Seleccione una Maquina:</label>
        <select class="form-control form-select" id="Maquina">
            <option>Seleccione....</option>
            <option>SMT1</option>
            <option>SMT2</option>
            <option>SMT3</option>
            <option>SMT4</option>
            <option>SMT5</option>
            <option>SMT6</option>
            <option>SMT7</option>
            <option>SMT8</option>
            <option>MCA CLUSTER</option>
            <option>MCA DISPLAY</option>
        </select>
    </div>

    <div class="col-md-3">
        <label class="fs-3 fw-bold" for="Cargo_Paro">Cargar paro de Linea a:</label>
        <select class="form-control form-select" id="Cargar_Paro">
            <option>Seleccione....</option>
            <option>Evento 1 TBD</option>
            <option>Evento 2 TBD</option>
            <option>Evento 3 TBD</option>
            <option>Evento 4 TBD</option>
            <option>Evento 5 TBD</option>
        </select>
    </div>
    <div class="col-md-3">
        <label class="fs-3 fw-bold" for="Empleado">¿Numero de Empleado?</label>
        <input type="text" class="form-control" id="Empleado" placeholder="Ejemplo >> 763" />
    </div>

    <div class="col-md-3">
        <label class="fs-3 fw-bold" for="Ticket">No Ticket creado</label>
        <input type="text" class="form-control" id="Ticket" placeholder="Ejemplo >> INC000001" />
    </div>
    <div class="col-md-3">
        <label class="fs-3 fw-bold" for="EWO">No de EWO creado</label>
        <input type="text" class="form-control" id="EWO" />
    </div>
    <div class="col-md-12">
        <textarea class="form-control" placeholder="Comentarios adicionales del reporte....."></textarea>
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-success fs-3">PROCESAR</button>
    </div>
</form>

<br />
<br />
<script src="~/Scripts/popper.js"></script>

Views/Process/Ejemplo_Formulario.cshtml
@model IRS.Models.ViewModels.Saludo
@{
    ViewBag.Title = "Ejemplo Formulario";
}

<h2>Formulario de Ejemplo</h2>
<hr />
<div class="container">
   
    @using (Html.BeginForm("Saludo","Process",FormMethod.Post))
    {

        <div class="row">
            <div class="col-md-2">
                <label class="control-label">Nombre</label>
            </div>
            <div class="col-md-3">
                @Html.TextBoxFor(s => s.nombre, new { @class = "form-control" })
                @Html.ValidationMessageFor(s => s.nombre, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-2">
                <label class="control-label">Edad</label>
            </div>
            <div class="col-md-3">
                @Html.TextBoxFor(s => s.edad, new { @class = "form-control" })
                @Html.ValidationMessageFor(s=>s.edad, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label class="control-label">Apellido</label>
            </div>
            <div class="col-md-3">
                @Html.TextBoxFor(s => s.apellido, new { @class = "form-control" })
            </div>
            <div class="col-md-2">
                <label class="control-label">Color</label>
            </div>
            <div class="col-md-3">
                @Html.TextBoxFor(s => s.color, new { @class = "form-control" })
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2">
                <label class="control-label">Dirección</label>
            </div>
            <div class="col-md-3">
                @Html.TextAreaFor(s => s.direccion, new { @class = "form-control" })
            </div>
            
        </div>
        <br />
        <div class="row">
            <div class="col-md-1">
                <input type="submit" name="name" value="Enviar" class="btn btn-success" />
            </div>

        </div>



    }

</div>

Views/Process/Error_Codes.cshtml
@{
    ViewBag.Title = "Error_Codes";
}

<h2>Error_Codes</h2>

Views/Process/History_Check.cshtml
@{
    ViewBag.Title = "History_Check";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>History_Check</h2>

Views/Process/History_Check_Selectivos.cshtml
@{
    ViewBag.Title = "History_Check_Selectivos";
}

<h1 class="text-primary fw-bold">Detalle History Check *Estaciones de Selectivos*</h1>
<hr />
<div class="container">
    <form action="History_Check_Selectivos" method="post">
        <input type="text" name="serie" value="" />
        <input type="submit" value="Buscar">
    </form>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Serie</th>
                        <th>Secuencia</th>
                        <th>Fecha</th>
                        <th>Mensaje</th>
                        <th>Linea</th>
                        <th>Estación</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.SerialNumber</td>
                            <td>@item.Sequence</td>
                            <td>@item.TimeDone</td>
                            <td>@item.Message</td>
                            <td>@item.LineID</td>
                            <td>@item.StationID</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Views/Process/Kamishibai_Board.cshtml
@{
    ViewBag.Title = "Kamishibai_Board";
}

<h2>Kamishibai_Board</h2>

Views/Process/OEE_Reporting.cshtml
@{
    ViewBag.Title = "OEE_Reporting";
}

<h2>OEE_Reporting</h2>

Views/Process/Trace_Errors.cshtml
@{
    ViewBag.Title = "Trace_Errors";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Trace_Errors</h2>

<hr />
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-sm">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <form class="d-flex">
                <input class="form-control me-3" type="search" placeholder="Buscar..." aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>

</nav>
<br />

<div class="container">
    <table class="table table-bordered align-middle">
        <thead>
            <tr class="table-primary">
                <th scope="col">Proceso</th>
                <th scope="col">Nombre del Archivo</th>
                <th scope="col">TimeDate</th>
                <th scope="col">Message</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var x in Model)
            {
                <tr>
                    <td>@x.Maquina</td>
                    <td>@x.FileName</td>
                    <td>@x.TimeDate</td>
                    <td>@x.Message</td>
            </tr>
        }
        </tbody>
    </table>
</div>

Views/Process/Valor_Declaration.cshtml
@{
    ViewBag.Title = "Valor_Declaration";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Valor_Declaration</h2>