Controllers/AssetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IRS.Services;
/// <summary>
/// J Mendoza and N George
/// </summary>
namespace IRS.Controllers
{
    public class AssetsController : Controller
    {
        readonly HardwareService hws = new HardwareService();
        readonly SoftwareServices sws = new SoftwareServices();
        readonly PhoneServices phones = new PhoneServices();

       


        public ActionResult Assets_Menu()
        {
            return View();

        }
       //Actions para formularios

        public ActionResult Add_Hardware_Form()
        {
            return View();
        }
        



        //***********Actions para consultas*********

        public ActionResult Master_Hardware()
        {
          
            var modelo = hws.Consultar_Hardware();
            return View(modelo);
        }

        public ActionResult MasterPhone() 
        {
            var modelo=phones.ConsultarCelulares();
            return View(modelo);
        }

        public ActionResult ConsultarCelulares()
        {
            var modelo = phones.ConsultarCelulares();
            return View(modelo);
        }


        public ActionResult Master_Software()
        {

            var result = sws.Get_Software();
            return View(result);
        }

        public ActionResult Get_Anexos()
        {
            var result = hws.Obtener_Anexos();

            return View(result);
        }

        public ActionResult Add_Employees()
        {
           

            return View();
        }


        public ActionResult Add_Hardware()
        {


            return View();
        }

        public ActionResult Add_Modelo_Hardware()
        {


            return View();
        }

        public ActionResult Add_Phone()
        {


            return View();
        }

        public ActionResult Add_Software()
        {


            return View();
        }

        public ActionResult Add_Vendor()
        {


            return View();
        }
    }
}

Views/Assets/Add_Employees.cshtml
@{
    ViewBag.Title = "Add_Employees";
}

<h2 class="page-header">Agregar Empleado</h2>

<br>
<div class="form-horizontal ">

    <form action="~/Home/Index" method="post">

        <div class="row">

            <div class="col-md-1">
                <label> #Employees</label>
            </div>
            <div class="col-md-3">
                <input type="text" class="form-control" autofocus required />

            </div>


        </div>

        <br>

        <div class="row">

            <div class="col-md-1">
                <label> First Name</label>
            </div>
            <div class="col-md-3">
                <input type="text" class="form-control" autofocus required />

            </div>

            <div class="col-md-1">
                <label> Last Name</label>
            </div>
            <div class="col-md-3">
                <input type="text" class="form-control" autofocus required />

            </div>



        </div>
        <br>

        <div class="row">

            <div class="col-md-1">
                <label class="control-label">Position</label>
            </div>
            <div class="col-md-3">
                <select class="form-control" aria-label="Position" autofocus required>
                    <option disabled selected value="Espacio">     </option>
                    <option value="AL MANAGER">AL MANAGER</option>
                    <option value="BECARIO">BECARIO</option>
                    <option value="CALIDAD">CALIDAD</option>
                    <option value="COMPRAS">COMPRAS</option>
                    <option value="DESARROLLO">DESARROLLO</option>
                    <option value="FINANZAS">FINANZAS</option>
                    <option value="ICT">ICT</option>
                    <option value="ICT MANAGER">ICT MANAGER</option>
                    <option value="INFRASTRUCTURE COORDINATOR">INFRASTRUCTURE COORDINATOR</option>
                    <option value="INGENIERIA">INGENIERIA</option>
                    <option value="JEFE DE SEGURIDAD">JEFE DE SEGURIDAD</option>
                    <option value="LOGISTICA">LOGISTICA</option>
                    <option value="MANAGER">MANAGER</option>
                    <option value="MANTENIMIENTO">MANTENIMIENTO</option>
                    <option value="METODOS">METODOS</option>
                    <option value="MOLDES">MOLDES</option>
                    <option value="PRODUCCION">PRODUCCION</option>
                    <option value="PROJECT MANAGER">PROJECT MANAGER</option>
                    <option value="RD">RD</option>
                    <option value="RECURSOS HUMANOS">RECURSOS HUMANOS</option>
                    <option value="SEGURIDAD">SEGURIDAD</option>
                    <option value="SUPERVISOR">SUPERVISOR</option>
                    <option value="TESTING">TESTING</option>

                </select>

            </div>




            <div class="col-md-1">
                <label class="control-label">Employed By</label>
            </div>
            <div class="col-md-3">
                <select class="form-control" aria-label="Employed By" autofocus required>
                    <option disabled selected value="VACIO">   </option>
                    <option value="MM">MM</option>
                    <option value="Outsourse">Outsourse</option>


                </select>


            </div>
        </div>

        <br>
        <div class="row">


            <div class="col-md-1">
                <label class="control-label">Departament</label>
            </div>
            <div class="col-md-3">
                <select class="form-control" aria-label="Departament" autofocus required>
                    <option disabled selected value="Espacio">     </option>
                    <option value="MM-RH">MM-RH</option>
                    <option value="MM-LOGISTICA">MM-LOGISTICA</option>
                    <option value="MM-IT">MM-IT</option>
                    <option value="MM-COMPRAS">MM-COMPRAS</option>
                    <option value="MM-DIRECCION">MM-DIRECCION</option>
                    <option value="MM-EHS">MM-EHS</option>
                    <option value="MM-TECNOLOGIA">MM-TECNOLOGIA</option>
                    <option value="MM-CALIDAD">MM-CALIDAD</option>
                    <option value="RYD">RYD</option>
                    <option value="MM-FINANZAS">MM-FINANZAS</option>
                    <option value="MM-PROCESOS">MM-PROCESOS</option>
                    <option value="MM-MANTENIMIENTO">MM-MANTENIMIENTO</option>
                    <option value="MM-METODOS">MM-METODOS</option>
                    <option value="MM-PRODUCCION">MM-PRODUCCION</option>
                    <option value="AL-RH">AL-RH</option>
                    <option value="MM-TESTING">MM-TESTING</option>
                    <option value="MM-TESTING">MM-TESTING</option>
                    <option value="MM-GKD">MM-GKD</option>
                    <option value="MM-PLASTICOS">MM-PLASTICOS</option>
                    <option value="MM-PP&amp;C">MM-PP&amp;C</option>
                    <option value="MM-SEGURIDAD PATRIMONIAL">MM-SEGURIDAD PATRIMONIAL</option>
                    <option value="MM-SERIGRAFIA">MM-SERIGRAFIA</option>
                    <option value="AL-PRODUCCION">AL-PRODUCCION</option>
                    <option value="AL-MANTENIMIENTO">AL-MANTENIMIENTO</option>
                    <option value="AL-LOGISTICA">AL-LOGISTICA</option>
                    <option value="AL-FINANZAS">AL-FINANZAS</option>
                    <option value="AL-DIRECCION">AL-DIRECCION</option>
                    <option value="AL-PREPRODUCCION">AL-PREPRODUCCION</option>
                    <option value="AL-MANUFACTURA">AL-MANUFACTURA</option>
                    <option value="AL-PROCESOS">AL-PROCESOS</option>
                    <option value="AL-CALIDAD">AL-CALIDAD</option>
                    <option value="AL-PP&amp;C/MMS">AL-PP&amp;C/MMS</option>
                    <option value="AL-MOLDES">AL-MOLDES</option>

                </select>


            </div>


            <div class="col-md-1">
                <label> Creation</label>
            </div>
            <div class="col-md-3">
                <input type="datetime-local" class="form-control" autofocus required />

            </div>

        </div>

        <br>


        <div class="row">


            <div class="col-md-1">
                <label class="control-label">Manager</label>

            </div>
            <div class="col-md-3">
                <select class="form-control" aria-label="Manager" autofocus required>
                    <option disabled selected value="Espacio">   </option>
                    <option value="425">BALTAZAR HUERTA, JHONNY</option>
                    <option value="40001234">BUSTOS, CESAR</option>
                    <option value="1000481">CANELA SIMO, SERGIO</option>
                    <option value="1000554">DE LA CRUZ, HORACIO</option>
                    <option value="559">ESTRADA, ISRAEL </option>
                    <option value="1000498">FERNANDEZ, GONZALO</option>
                    <option value="1000512">FIERRO REYES, ALEJANDRO</option>
                    <option value="101">FOURNIER, DAVID</option>
                    <option value="3912">GALLARDO ARROYO, GIOVANNI</option>
                    <option value="1000516">GOMEZ MOYA, MIGUEL ANGEL</option>
                    <option value="1000518">GONZALEZ CORTEZ, JOSE LUIS </option>
                    <option value="1000524">HERNANDEZ PERALES, PABLO </option>
                    <option value="9071">LOPEZ LOPEZ, IVAN VIDAL</option>
                    <option value="904">LOPEZ TORREBLANCA, RODRIGO</option>
                    <option value="1000514">MARIN, ARMANDO </option>
                    <option value="9030">MARTINEZ PEDROZA, EYVAR HAZIEL</option>
                    <option value="338">MEJIA FABIAN, CARLOS</option>
                    <option value="10003843">MONTECINOS, JONATHAN</option>
                    <option value="1000478">MORALES, JUAN CARLOS</option>
                    <option value="700">PEÑA, DANIEL </option>
                    <option value="1000468">RAMIREZ BALTAZAR, SIMON</option>
                    <option value="9061">RIOS, JUAN ANTONIO </option>
                    <option value="1000522">RIOS MARRON, OSCAR ARMANDO</option>
                    <option value="756">ROA, OSCAR GUILLERMO </option>
                    <option value="548">RODRIGUEZ, DARIO </option>
                    <option value="1000526">SANCHEZ GARCIA, MARIO</option>
                    <option value="1000528">ESCOBAR, GEMMA</option>



                </select>


            </div>

            <div class="col-md-1 ">
                <label class="control-label">Site</label>
            </div>
            <div class="col-md-2">
                <select class="form-control" aria-label="Site" autofocus required>
                    <option disabled selected value="Espacio">     </option>
                    <option value="TEPO">TEPO</option>
                    <option value="TOLUCA">TOLUCA</option>


                </select>


            </div>


        </div>

        <br>

        <div class="row">

            <div class="col-md-1">
                <label> Stop Date</label>
            </div>
            <div class="col-md-3">
                <input type="text" class="form-control " autofocus required />

            </div>


            <div class="col-md-1">
                <label class="control-label">Status</label>
            </div>
            <div class="col-md-1">
                <select class="form-control" aria-label="Status" autofocus required>
                    <option disabled selected value="Espacio">     </option>
                    <option value="A">A</option>
                    <option value="B">B</option>


                </select>




            </div>
            <div class="col-md-5">
                <label class="control-label">A- Active B- No Active</label>
            </div>



        </div>

        <br>

        <div class="row">

            <div class="col-md-1">
                <label> Remarks</label>
            </div>
            <div class="col-md-3">
                <textarea type="text" class="form-control" placeholder="Remarks" autofocus required style="width:325px; height: 100px;">
                </textarea>

            </div>


            <div class="col-md-1">
                <label>Cost Center</label>
            </div>
            <div class="col-md-3">
                <input type="text" class="form-control" autofocus required />

            </div>



        </div>
        <br>

        <div class="row">


            <div class="col-md-offset-6 col-md-1 ">
                <input type="submit" value="Enviar" class="btn btn-success">

            </div>


            <div class=" col-md-1 ">
                <input type="submit" value="Cancel" class="btn btn-danger">

            </div>

        </div>







    </form>

</div>

Views/Assets/Add_Modelo_Hardware.cshtml
@{
    ViewBag.Title = "Add_Modelo_Hardware";
}

<h2> Agregar Modelo Hardaware</h2>

<hr>
<div class="form-horizontal">



    <form action="~/Home/Index" method="post">

        <div class="row">

            <div class="col-md-1">
                <label>Model</label>
            </div>
            <div class="col-md-2">
                <input type="text" class="form-control" autofocus required />

            </div>




        </div>

        <br>

        <div class="row">



            <div class="col-md-1">
                <label>Speed(Mhz):</label>
            </div>
            <div class="col-md-2">
                <input type="text" class="form-control" autofocus required />

            </div>


            <div class="col-md-1">
                <label>Memory(MB):</label>
            </div>
            <div class="col-md-2">
                <input type="text" class="form-control" autofocus required />

            </div>

            <div class="col-md-1">
                <label>HD(GB):</label>
            </div>
            <div class="col-md-2">
                <input type="text" class="form-control" autofocus required />

            </div>





        </div>


        <br>


        <div class="row">

            <div class="col-md-1">
                <label>Vendor</label>
            </div>
            <div class="col-md-3">
                <input type="text" class="form-control" autofocus required />

            </div>


            <div class="col-md-1">
                <label>Type</label>
            </div>

            <div class="col-md-3">
                <select class="form-control" aria-label="Type" autofocus required>
                    <option disabled selected value="Espacio">   </option>
                    <option value="tepo">BOCINA</option>
                    <option value="tol">CAMARA</option>
                    <option value="tepo">DESKTOP</option>
                    <option value="tol">LAPTOP</option>
                    <option value="tepo">MONITOR</option>
                    <option value="tol">PRINTER</option>
                    <option value="tepo">PROYECTOR</option>
                    <option value="tol">ESCANNER</option>
                    <option value="tepo">SERVIDOR</option>
                    <option value="tol">SWITCH</option>
                    <option value="tepo">TELEFONO FIJO</option>
                    <option value="tol">UPS</option>
                    <option value="tepo">LECTOR</option>
                    <option value="tol">BASE HAND HELD</option>
                    <option value="tepo">DOCKING STATION</option>






                </select>



            </div>



        </div>

        <br>


        <div class="row">

            <div class="col-md-1">
                <label>Operator</label>
            </div>
            <div class="col-md-3">
                <input type="text" class="form-control" autofocus required />

            </div>



            <div class="col-md-1">
                <label>Create Date</label>
            </div>
            <div class="col-md-3">
                <input type="date" class="form-control" autofocus required />

            </div>


        </div>

        <br>


        <div class="row">

            <div class="col-md-offset-1 col-md-1">
                <input type="submit" value="Enviar" class="btn btn-success">

            </div>



            <div class=" col-md-1 ">
                <input type="submit" value="Cancel" class="btn btn-danger">

            </div>

        </div>

    </form>


</div>

Views/Assets/Add_Software.cshtml
@{
    ViewBag.Title = "Add_Software";
}

<h2>Agregar Software</h2>

<hr>
<div class="form-horizontal">



    <form action="~/Home/Index" method="post">

        <div class="row">

            <div class="col-md-1">
                <label>Software Title</label>
            </div>
            <div class="col-md-3">
                <input type="text" class="form-control" autofocus required />

            </div>




        </div>

        <br>

        <div class="row">



            <div class="col-md-1">
                <label>Vendor:</label>
            </div>
            <div class="col-md-3">
                <input type="text" class="form-control" autofocus required />

            </div>

        </div>


        <br>


        <div class="row">

            <div class="col-md-1">
                <label>Purchase Licences:</label>
            </div>
            <div class="col-md-3">
                <input type="text" class="form-control" autofocus required />

            </div>


        </div>

        <br>

        <div class="row">

            <div class="col-md-1">
                <label>Purchased by (Site):</label>
            </div>

            <div class="col-md-1">
                <select class="form-control" aria-label="Type" autofocus required>
                    <option disabled selected value="Espacio">   </option>
                    <option value="tepo">TEPO</option>
                    <option value="tol">TOL</option>


                </select>



            </div>

        </div>

        <br>


        <div class="row">

            <div class="col-md-1">
                <label>PO Number:</label>
            </div>
            <div class="col-md-3">
                <input type="text" class="form-control" autofocus required />

            </div>




        </div>

        <br>

        <div class="row">

            <div class="col-md-1">
                <label>KEY Licence:</label>
            </div>
            <div class="col-md-3">
                <input type="text" class="form-control" autofocus required />

            </div>




        </div>

        <br>


        <div class="row">

            <div class="col-md-1">
                <label>Is a MM Standard:</label>
            </div>

            <div class="col-md-1">
                <select class="form-control" aria-label="Type" autofocus required>
                    <option disabled selected value="Espacio">   </option>
                    <option value="tepo">TEPO</option>
                    <option value="tol">TOL</option>


                </select>



            </div>

        </div>

        <br>


        <div class="row">

            <div class="col-md-offset-2 col-md-1">
                <input type="submit" value="Enviar" class="btn btn-success">

            </div>



            <div class=" col-md-1 ">
                <input type="submit" value="Cancel" class="btn btn-danger">

            </div>

        </div>

    </form>


</div>

Views/Assets/Assets_Apps.cshtml
@{
    ViewBag.Title = "Assets_Apps";
}




<section class="row g-3 gx-5 gy-5">
    <div class="card col-md-4">
        <h5 class="card-header">Hardware Inventory</h5>
        <div class="card-body">
            <h5 class="card-title">Detalle de Inventario de Computo</h5>
            <p class="card-text">Pagina que muestra el inventario de computo</p>
            <a href=@Url.Action("Add_Hardware" , "Assets") class="btn btn-primary">Go</a>
        </div>
    </div>
    <div class="card col-md-4">
        <h5 class="card-header">Software Inventory</h5>
        <div class="card-body">
            <h5 class="card-title">Detalle de Inventario de Software</h5>
            <p class="card-text">Pagina que muestra el inventario de Sofware</p>
            <a href=@Url.Action("Add_Software" , "Assets") class="btn btn-primary">Go</a>
        </div>
    </div>
    <div class="card col-md-4">
        <h5 class="card-header">Acounts</h5>
        <div class="card-body">
            <h5 class="card-title">Tpos de cuentas</h5>
            <p class="card-text">Pagina que muestra el inventario de cuents.</p>
            <a href=@Url.Action("Error_Codes" , "Process") class="btn btn-primary">Go</a>
        </div>
    </div>

    <div class="card col-md-4">
        <h5 class="card-header">Kiosko Configuration</h5>
        <div class="card-body">
            <h5 class="card-title">Detalle de Configuracion del Kiosco SMTs</h5>
            <p class="card-text">Pagina que muestra......</p>
            <a href=@Url.Action("Kiosk_Configuration" , "Process") class="btn btn-primary">Go</a>
        </div>
    </div>
    <div class="card col-md-4">
        <h5 class="card-header">PLC Activation</h5>
        <div class="card-body">
            <h5 class="card-title">Detalle de Activacion de PLC SMTs</h5>
            <p class="card-text">Pagina que muestra......</p>
            <a href=@Url.Action("PLC_Activation" , "Process") class="btn btn-primary">Go</a>
        </div>
    </div>
    <div class="card col-md-4">
        <h5 class="card-header">OEE Reporting</h5>
        <div class="card-body">
            <h5 class="card-title">Detalle de OEE Reportado</h5>
            <p class="card-text">Pagina que muestra......</p>
            <a href=@Url.Action("OEE_Reporting" , "Process") class="btn btn-primary">Go</a>
        </div>
    </div>
    <div class="card col-md-4">
        <h5 class="card-header">System Errors</h5>
        <div class="card-body">
            <h5 class="card-title">Detalle de......</h5>
            <p class="card-text">Pagina que muestra......</p>
            <a href=@Url.Action("System_Erros" , "Process") class="btn btn-primary">Go</a>
        </div>
    </div>
    <div class="card col-md-4">
        <h5 class="card-header">Trace Errors</h5>
        <div class="card-body">
            <h5 class="card-title">Detalle de......</h5>
            <p class="card-text">Pagina que muestra......</p>
            <a href=@Url.Action("Trace_Errors" , "Process") class="btn btn-primary">Go</a>
        </div>
    </div>
    <div class="card col-md-4">
        <h5 class="card-header">Trace History Check</h5>
        <div class="card-body">
            <h5 class="card-title">Detalle de......</h5>
            <p class="card-text">Pagina que muestra......</p>
            <a href=@Url.Action("History_Check" , "Process") class="btn btn-primary">Go</a>
        </div>
    </div>
    <div class="card col-md-4">
        <h5 class="card-header">Traceability Desactivation</h5>
        <div class="card-body">
            <h5 class="card-title">Detalle de......</h5>
            <p class="card-text">Pagina que muestra......</p>
            <a href=@Url.Action("Trace_Desactivation" , "Process") class="btn btn-primary">Go</a>
        </div>
    </div>
    <div class="card col-md-4">
        <h5 class="card-header">Valor Declaration</h5>
        <div class="card-body">
            <h5 class="card-title">Detalle de......</h5>
            <p class="card-text">Pagina que muestra......</p>
            <a href=@Url.Action("Valor_Declaration" , "Process") class="btn btn-primary">Go</a>
        </div>
    </div>
</section>

Views/Assets/Assets_Menu.cshtml
@{
    ViewBag.Title = "Assets Menu";
}

<div class="row ">
    <div class="col-md-4 col-sm-4 col-lg-4">
        <div class="card border-danger">
            <h5 class="card-header text-white bg-danger">Master Hardware</h5>
            <div class="card-body text-white bg-primary">
                <h5 class="card-title">Hardware Inventory</h5>
                <p class="card-text">Look at Marelli Hardware Inventory</p>
                <a href=@Url.Action("Master_Hardware" , "Assets") class="btn btn-danger">Ir</a>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-4 col-lg-4">
        <div class="card border-danger">
            <h5 class="card-header text-white bg-danger">Directorio Telefonico</h5>
            <div class="card-body text-white bg-primary">
                <h5 class="card-title">Detalle de Numeros celulares</h5>
                <p class="card-text">Página que muestra el directorio celular</p>
                <a href=@Url.Action("MasterPhone" , "Assets") class="btn btn-danger">Ir</a>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-4 col-lg-4">
        <div class="card border-danger">
            <h5 class="card-header text-white bg-danger">Error Codes</h5>
            <div class="card-body text-white bg-primary">
                <h5 class="card-title">Detalle de Código de Errores</h5>
                <p class="card-text">Página que muestra los códigos de error en lineas de producción</p>
                <a href=@Url.Action("Error_Codes" , "Assets") class="btn btn-danger">Ir</a>
            </div>
        </div>
    </div>
</div>
<br />
<div class="row">

    <div class="col-md-4 col-sm-4 col-lg-4">
        <div class="card border-danger">
            <h5 class="card-header text-white bg-danger">Kiosko Configuration</h5>
            <div class="card-body text-white bg-primary">
                <h5 class="card-title">Configuracion del Kiosco SMTs</h5>
                <p class="card-text">Página que muestra los detalles de configuración del Kisko para las lineas SMT</p>
                <a href=@Url.Action("Kiosk_Configuration" , "Assets") class="btn btn-danger">Ir</a>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-4 col-lg-4">
        <div class="card border-danger">
            <h5 class="card-header text-white bg-danger">PLC Activation</h5>
            <div class="card-body text-white bg-primary">
                <h5 class="card-title">Detalle de Activacion de PLC SMTs</h5>
                <p class="card-text">Página que muestra los PLC disponubles para ser activados</p>
                <a href=@Url.Action("PLC_Activation" , "Assets") class="btn btn-danger">Ir</a>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-4 col-lg-4">
        <div class="card border-danger">
            <h5 class="card-header text-white bg-danger">OEE Reporting</h5>
            <div class="card-body text-white bg-primary">
                <h5 class="card-title">Detalle de OEE Reportado</h5>
                <p class="card-text">Página que muestra el detalle del reporte OEE</p>
                <a href=@Url.Action("OEE_Reporting" , "Assets") class="btn btn-danger">Ir</a>
            </div>
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-4 col-sm-4 col-lg-4">
        <div class="card border-danger">
            <h5 class="card-header text-white bg-danger">System Errors</h5>
            <div class="card-body text-white bg-primary">
                <h5 class="card-title">Detalle los errores del Sistema</h5>
                <p class="card-text">Página que muestra el hitórico de errores en el sistema</p>
                <a href=@Url.Action("System_Erros" , "Assets") class="btn btn-danger">Ir</a>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-4 col-lg-4">
        <div class="card border-danger">
            <h5 class="card-header text-white bg-danger">Trace Errors</h5>
            <div class="card-body text-white bg-primary">
                <h5 class="card-title">Detalle de errores de trazabilidad</h5>
                <p class="card-text">Página que muestra el histórico de los errores en el proceso de trazabilidad</p>
                <a href=@Url.Action("Trace_Errors" , "Assets") class="btn btn-danger">Ir</a>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-4 col-lg-4">
        <div class="card border-danger">
            <h5 class="card-header text-white bg-danger">Trace History Check</h5>
            <div class="card-body text-white bg-primary">
                <h5 class="card-title">Detalle del History Check</h5>
                <p class="card-text">Página que muestra el detalle del proceso History Check.</p>
                <a href=@Url.Action("History_Check" , "Assets") class="btn btn-danger">Ir</a>
            </div>
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-4 col-sm-4 col-lg-4">
        <div class="card border-danger">
            <h5 class="card-header text-white bg-danger">Traceability Desactivation</h5>
            <div class="card-body text-white bg-primary">
                <h5 class="card-title">Desactivación de trazabilidad</h5>
                <p class="card-text">Página que muestra la desactivación de trazabilidad</p>
                <a href=@Url.Action("Trace_Desactivation" , "Assets") class="btn btn-danger">Ir</a>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-4 col-lg-4">
        <div class="card border-danger">
            <h5 class="card-header text-white bg-danger">Valor Declaration</h5>
            <div class="card-body text-white bg-primary">
                <h5 class="card-title">Detalle del proceso de declaración</h5>
                <p class="card-text">Página que muestra el detalle del proceso de declaración</p>
                <a href=@Url.Action("Valor_Declaration" , "Assets") class="btn btn-danger">Ir</a>
            </div>
        </div>
    </div>
</div>

Views/Assets/Get_Anexos.cshtml
@{
    ViewBag.Title = "Get_Anexos";
}

<h2>Anexos</h2>

<table class="table table-responsive">
    <thead class="table-dark">
        <tr>
            <td>Serial Number</td>
            <td>Anexo</td>
            <td>Anexo Number</td>
            <td>Encontrado</td>

        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.SerialNumber</td>
                <td>@x.Anexo</td>
                <td>@x.AnexoNumber</td>
                <td>@x.Encontrado</td>
            </tr>
        }
    </tbody>
</table>

Views/Assets/Master_Software.cshtml
@{
    ViewBag.Title = "Master_Software";
}

<h2>Master_Software</h2>

<table>
    <tr>
        <td>Nombre</td>
        <td>Proveedor</td>
       
    </tr>
    @foreach(var x in Model)
            { 
             <tr>
                 <td>@x.SoftwareName</td>
                <td>@x.Vendor</td>
             </tr>
            }
</table>